version: "3.7"
services:

  mysql-1:
    image: "mysql:8.0.34"
    container_name: "mysql-1"
    hostname: "mysql-1"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: "mysqld --server-id=1 --log-bin=mysql-bin --binlog-format=MIXED --auto-increment-increment=2 --auto-increment-offset=1"
    volumes:
      - ./init-mysql-1:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 5s
      retries: 2
      start_period: 20s

  mysql-2:
    image: "mysql:8.0.34"
    container_name: "mysql-2"
    hostname: "mysql-2"
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: "mysqld --server-id=2 --log-bin=mysql-bin --binlog-format=MIXED --auto-increment-increment=2 --auto-increment-offset=2"
    volumes:
      - ./init-mysql-2:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 5s
      retries: 2
      start_period: 20s