CREATE SCHEMA `SPRING`;
GRANT ALL PRIVILEGES ON `SPRING`.* TO 'user'@'%';

CREATE USER 'replicator'@'%' IDENTIFIED BY 'replpass';
GRANT REPLICATION SLAVE ON *.* TO 'replicator'@'%';

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='mysql-2',
  SOURCE_USER='replicator',
  SOURCE_PASSWORD='replpass',
  SOURCE_LOG_FILE='mysql-bin.000003',
  GET_SOURCE_PUBLIC_KEY=1;

START REPLICA;
